description: Validates any values-based axis
allOf:
  - $ref: valuesAxisBase.yaml
  - if:
      not:
        required:
          - dataType
    then:
      $ref: primitiveValuesAxis.yaml
dependentSchemas:
  dataType:
    allOf:
      - if:
          properties:
            dataType:
              const: tuple
        then:
          $ref: tupleValuesAxis.yaml
      - if:
          properties:
            dataType:
              const: polygon
        then:
          $ref: polygonValuesAxis.yaml
