name: Test build OpenAPI bundle

on:
  pull_request:
    branches:
      - master
    paths:
      - 'core/standard/openapi/**.yaml'

jobs:
  test-build-openapi-bundle:
    name: Generate OpenAPI bundle
    runs-on: ubuntu-latest
    steps:
    - name: Setup npm
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install @redocly/cli -g
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
      #with:
      #  fetch-depth: 0
    - name: Generate OpenAPI 3.0 bundle
      run: |
        cd core/standard/openapi
        redocly bundle -o ogcapi-environmental-data-retrieval-1-oas30.bundled.json ogcapi-environmental-data-retrieval-1-oas30.yaml
    - name: Generate OpenAPI 3.1 bundle
      run: |
        cd core/standard/openapi       
        redocly bundle -o ogcapi-environmental-data-retrieval-1-oas31.bundled.json ogcapi-environmental-data-retrieval-1-oas31.yaml

