name: Test build OpenAPI bundle

on:
  pull_request:
    branches:
      - master
    paths:
      - 'core/standard/openapi/**.yaml'

jobs:
  test-build-openapi-bundle:
    name: Generate OpenAPI bundle
    runs-on: ubuntu-latest
    steps:
    - name: Setup npm
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install -g @apidevtools/swagger-cli
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
      #with:
      #  fetch-depth: 0
    - name: Generate OpenAPI bundle
      run: |
        cd core/standard/openapi
        swagger-cli bundle -o ogcapi-environmental-data-retrieval-1.bundled.json ogcapi-environmental-data-retrieval-1.yaml

